from rag import RAGClass
from web_scraper import ArxivScraper
from langchain_community.document_loaders import PyMuPDFLoader
import os
from huggingface_hub import login
import sqlite3

# keyword_extractor = pipeline("zero-shot-classification", model="facebook/bart-large-mnli",  device_map="auto")

# if os.path.exists("./homework/mydata.db"):
#     os.remove("./homework/mydata.db")
# # Create database schema first
# create_database_schema("./homework/mydata.db")

conn = sqlite3.connect("./homework/mydata.db")

conn.commit()

list_urls = [
    "https://arxiv.org/list/econ.EM/recent"
]
scraper = ArxivScraper(delay=2)
articleUlrs = scraper.get_article_urls_from_list_page( "https://arxiv.org/list/econ.EM/recent");

pdf_folder = "./pdfs"
if not os.path.exists(pdf_folder) and os.listdir(pdf_folder).count() == 0:
    scraper.download_pdfs(articleUlrs)

    # Load all pdfs from ./pdfs folder
docs = []
for fname in os.listdir(pdf_folder):
    if fname.lower().endswith('.pdf'):
        loader = PyMuPDFLoader(os.path.join(pdf_folder, fname))
        docs.extend(loader.load())

rag = RAGClass(docs)
rag.split_documents()
rag.convert_text_to_embeddings_with_faiss();

for i, doc in enumerate(rag.text_chunks):
    # Insert the document and get its autogenerated id
    cursor = conn.execute("INSERT INTO documents (title, author, year, keywords) VALUES (?, ?, ?, ?)", 
                          (doc.metadata["title"], doc.metadata["author"], '', ''))
    doc_id = cursor.lastrowid
    # Insert chunk text into FTS table, linking by rowid (using document id)
    conn.execute("INSERT INTO chunks(doc_id, chunk_index, text_content) VALUES (?, ?, ?)", (doc_id, i, doc.page_content))

conn.commit()
